/*
 * Zuora Copy
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.zuora.prototype.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BillToContact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-20T00:16:03.519Z")



public class BillToContact {
  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("county")
  private String county = null;

  @SerializedName("fax")
  private String fax = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("homePhone")
  private String homePhone = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("mobilePhone")
  private String mobilePhone = null;

  @SerializedName("nickname")
  private String nickname = null;

  @SerializedName("otherPhone")
  private String otherPhone = null;

  @SerializedName("otherPhoneType")
  private String otherPhoneType = null;

  @SerializedName("personalEmail")
  private String personalEmail = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("taxRegion")
  private String taxRegion = null;

  @SerializedName("workEmail")
  private String workEmail = null;

  @SerializedName("workPhone")
  private String workPhone = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("contactDescription")
  private String contactDescription = null;

  public BillToContact address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public BillToContact address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public BillToContact city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public BillToContact country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public BillToContact county(String county) {
    this.county = county;
    return this;
  }

   /**
   * Get county
   * @return county
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCounty() {
    return county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public BillToContact fax(String fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFax() {
    return fax;
  }

  public void setFax(String fax) {
    this.fax = fax;
  }

  public BillToContact firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public BillToContact homePhone(String homePhone) {
    this.homePhone = homePhone;
    return this;
  }

   /**
   * Get homePhone
   * @return homePhone
  **/
  @ApiModelProperty(required = true, value = "")
  public String getHomePhone() {
    return homePhone;
  }

  public void setHomePhone(String homePhone) {
    this.homePhone = homePhone;
  }

  public BillToContact lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public BillToContact mobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
    return this;
  }

   /**
   * Get mobilePhone
   * @return mobilePhone
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMobilePhone() {
    return mobilePhone;
  }

  public void setMobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
  }

  public BillToContact nickname(String nickname) {
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public BillToContact otherPhone(String otherPhone) {
    this.otherPhone = otherPhone;
    return this;
  }

   /**
   * Get otherPhone
   * @return otherPhone
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOtherPhone() {
    return otherPhone;
  }

  public void setOtherPhone(String otherPhone) {
    this.otherPhone = otherPhone;
  }

  public BillToContact otherPhoneType(String otherPhoneType) {
    this.otherPhoneType = otherPhoneType;
    return this;
  }

   /**
   * Get otherPhoneType
   * @return otherPhoneType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOtherPhoneType() {
    return otherPhoneType;
  }

  public void setOtherPhoneType(String otherPhoneType) {
    this.otherPhoneType = otherPhoneType;
  }

  public BillToContact personalEmail(String personalEmail) {
    this.personalEmail = personalEmail;
    return this;
  }

   /**
   * Get personalEmail
   * @return personalEmail
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPersonalEmail() {
    return personalEmail;
  }

  public void setPersonalEmail(String personalEmail) {
    this.personalEmail = personalEmail;
  }

  public BillToContact state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(required = true, value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public BillToContact taxRegion(String taxRegion) {
    this.taxRegion = taxRegion;
    return this;
  }

   /**
   * Get taxRegion
   * @return taxRegion
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTaxRegion() {
    return taxRegion;
  }

  public void setTaxRegion(String taxRegion) {
    this.taxRegion = taxRegion;
  }

  public BillToContact workEmail(String workEmail) {
    this.workEmail = workEmail;
    return this;
  }

   /**
   * Get workEmail
   * @return workEmail
  **/
  @ApiModelProperty(required = true, value = "")
  public String getWorkEmail() {
    return workEmail;
  }

  public void setWorkEmail(String workEmail) {
    this.workEmail = workEmail;
  }

  public BillToContact workPhone(String workPhone) {
    this.workPhone = workPhone;
    return this;
  }

   /**
   * Get workPhone
   * @return workPhone
  **/
  @ApiModelProperty(required = true, value = "")
  public String getWorkPhone() {
    return workPhone;
  }

  public void setWorkPhone(String workPhone) {
    this.workPhone = workPhone;
  }

  public BillToContact postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public BillToContact contactDescription(String contactDescription) {
    this.contactDescription = contactDescription;
    return this;
  }

   /**
   * Get contactDescription
   * @return contactDescription
  **/
  @ApiModelProperty(required = true, value = "")
  public String getContactDescription() {
    return contactDescription;
  }

  public void setContactDescription(String contactDescription) {
    this.contactDescription = contactDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillToContact billToContact = (BillToContact) o;
    return Objects.equals(this.address1, billToContact.address1) &&
        Objects.equals(this.address2, billToContact.address2) &&
        Objects.equals(this.city, billToContact.city) &&
        Objects.equals(this.country, billToContact.country) &&
        Objects.equals(this.county, billToContact.county) &&
        Objects.equals(this.fax, billToContact.fax) &&
        Objects.equals(this.firstName, billToContact.firstName) &&
        Objects.equals(this.homePhone, billToContact.homePhone) &&
        Objects.equals(this.lastName, billToContact.lastName) &&
        Objects.equals(this.mobilePhone, billToContact.mobilePhone) &&
        Objects.equals(this.nickname, billToContact.nickname) &&
        Objects.equals(this.otherPhone, billToContact.otherPhone) &&
        Objects.equals(this.otherPhoneType, billToContact.otherPhoneType) &&
        Objects.equals(this.personalEmail, billToContact.personalEmail) &&
        Objects.equals(this.state, billToContact.state) &&
        Objects.equals(this.taxRegion, billToContact.taxRegion) &&
        Objects.equals(this.workEmail, billToContact.workEmail) &&
        Objects.equals(this.workPhone, billToContact.workPhone) &&
        Objects.equals(this.postalCode, billToContact.postalCode) &&
        Objects.equals(this.contactDescription, billToContact.contactDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address1, address2, city, country, county, fax, firstName, homePhone, lastName, mobilePhone, nickname, otherPhone, otherPhoneType, personalEmail, state, taxRegion, workEmail, workPhone, postalCode, contactDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillToContact {\n");
    
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    county: ").append(toIndentedString(county)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    homePhone: ").append(toIndentedString(homePhone)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    mobilePhone: ").append(toIndentedString(mobilePhone)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    otherPhone: ").append(toIndentedString(otherPhone)).append("\n");
    sb.append("    otherPhoneType: ").append(toIndentedString(otherPhoneType)).append("\n");
    sb.append("    personalEmail: ").append(toIndentedString(personalEmail)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    taxRegion: ").append(toIndentedString(taxRegion)).append("\n");
    sb.append("    workEmail: ").append(toIndentedString(workEmail)).append("\n");
    sb.append("    workPhone: ").append(toIndentedString(workPhone)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    contactDescription: ").append(toIndentedString(contactDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

