/*
 * Zuora Copy
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.zuora.prototype.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * CreateOrderNewUserRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-20T00:16:03.519Z")



public class CreateOrderNewUserRequest {
  @SerializedName("description")
  private String description = null;

  @SerializedName("orderNumber")
  private String orderNumber = null;

  @SerializedName("orderDate")
  private String orderDate = null;

  @SerializedName("newAccount")
  private NewAccount newAccount = null;

  @SerializedName("subscriptions")
  private List<Subscription> subscriptions = new ArrayList<Subscription>();

  public CreateOrderNewUserRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateOrderNewUserRequest orderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
  }

  public CreateOrderNewUserRequest orderDate(String orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * Get orderDate
   * @return orderDate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(String orderDate) {
    this.orderDate = orderDate;
  }

  public CreateOrderNewUserRequest newAccount(NewAccount newAccount) {
    this.newAccount = newAccount;
    return this;
  }

   /**
   * Get newAccount
   * @return newAccount
  **/
  @ApiModelProperty(required = true, value = "")
  public NewAccount getNewAccount() {
    return newAccount;
  }

  public void setNewAccount(NewAccount newAccount) {
    this.newAccount = newAccount;
  }

  public CreateOrderNewUserRequest subscriptions(List<Subscription> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public CreateOrderNewUserRequest addSubscriptionsItem(Subscription subscriptionsItem) {
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

   /**
   * Get subscriptions
   * @return subscriptions
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Subscription> getSubscriptions() {
    return subscriptions;
  }

  public void setSubscriptions(List<Subscription> subscriptions) {
    this.subscriptions = subscriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderNewUserRequest createOrderNewUserRequest = (CreateOrderNewUserRequest) o;
    return Objects.equals(this.description, createOrderNewUserRequest.description) &&
        Objects.equals(this.orderNumber, createOrderNewUserRequest.orderNumber) &&
        Objects.equals(this.orderDate, createOrderNewUserRequest.orderDate) &&
        Objects.equals(this.newAccount, createOrderNewUserRequest.newAccount) &&
        Objects.equals(this.subscriptions, createOrderNewUserRequest.subscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, orderNumber, orderDate, newAccount, subscriptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderNewUserRequest {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    newAccount: ").append(toIndentedString(newAccount)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

