/*
 * Zuora Copy
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.zuora.prototype.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * CreateSubscription
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-20T00:16:03.519Z")



public class CreateSubscription {
  @SerializedName("subscribeToRatePlans")
  private List<SubscribeToRatePlan> subscribeToRatePlans = new ArrayList<SubscribeToRatePlan>();

  @SerializedName("terms")
  private Terms terms = null;

  public CreateSubscription subscribeToRatePlans(List<SubscribeToRatePlan> subscribeToRatePlans) {
    this.subscribeToRatePlans = subscribeToRatePlans;
    return this;
  }

  public CreateSubscription addSubscribeToRatePlansItem(SubscribeToRatePlan subscribeToRatePlansItem) {
    this.subscribeToRatePlans.add(subscribeToRatePlansItem);
    return this;
  }

   /**
   * Get subscribeToRatePlans
   * @return subscribeToRatePlans
  **/
  @ApiModelProperty(required = true, value = "")
  public List<SubscribeToRatePlan> getSubscribeToRatePlans() {
    return subscribeToRatePlans;
  }

  public void setSubscribeToRatePlans(List<SubscribeToRatePlan> subscribeToRatePlans) {
    this.subscribeToRatePlans = subscribeToRatePlans;
  }

  public CreateSubscription terms(Terms terms) {
    this.terms = terms;
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @ApiModelProperty(required = true, value = "")
  public Terms getTerms() {
    return terms;
  }

  public void setTerms(Terms terms) {
    this.terms = terms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSubscription createSubscription = (CreateSubscription) o;
    return Objects.equals(this.subscribeToRatePlans, createSubscription.subscribeToRatePlans) &&
        Objects.equals(this.terms, createSubscription.terms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscribeToRatePlans, terms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSubscription {\n");
    
    sb.append("    subscribeToRatePlans: ").append(toIndentedString(subscribeToRatePlans)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

