/*
 * Zuora Copy
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.zuora.prototype.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * CreatePendingOrderExistingUserRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-20T00:16:03.519Z")



public class CreatePendingOrderExistingUserRequest {
  @SerializedName("description")
  private String description = null;

  @SerializedName("orderDate")
  private String orderDate = null;

  @SerializedName("existingAccountNumber")
  private String existingAccountNumber = null;

  @SerializedName("subscriptions")
  private List<Subscription> subscriptions = new ArrayList<Subscription>();

  public CreatePendingOrderExistingUserRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreatePendingOrderExistingUserRequest orderDate(String orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * Get orderDate
   * @return orderDate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(String orderDate) {
    this.orderDate = orderDate;
  }

  public CreatePendingOrderExistingUserRequest existingAccountNumber(String existingAccountNumber) {
    this.existingAccountNumber = existingAccountNumber;
    return this;
  }

   /**
   * Get existingAccountNumber
   * @return existingAccountNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getExistingAccountNumber() {
    return existingAccountNumber;
  }

  public void setExistingAccountNumber(String existingAccountNumber) {
    this.existingAccountNumber = existingAccountNumber;
  }

  public CreatePendingOrderExistingUserRequest subscriptions(List<Subscription> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public CreatePendingOrderExistingUserRequest addSubscriptionsItem(Subscription subscriptionsItem) {
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

   /**
   * Get subscriptions
   * @return subscriptions
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Subscription> getSubscriptions() {
    return subscriptions;
  }

  public void setSubscriptions(List<Subscription> subscriptions) {
    this.subscriptions = subscriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePendingOrderExistingUserRequest createPendingOrderExistingUserRequest = (CreatePendingOrderExistingUserRequest) o;
    return Objects.equals(this.description, createPendingOrderExistingUserRequest.description) &&
        Objects.equals(this.orderDate, createPendingOrderExistingUserRequest.orderDate) &&
        Objects.equals(this.existingAccountNumber, createPendingOrderExistingUserRequest.existingAccountNumber) &&
        Objects.equals(this.subscriptions, createPendingOrderExistingUserRequest.subscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, orderDate, existingAccountNumber, subscriptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePendingOrderExistingUserRequest {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    existingAccountNumber: ").append(toIndentedString(existingAccountNumber)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

