/*
 * Zuora Copy
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.zuora.prototype.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * OrderAction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-20T00:16:03.519Z")



public class OrderAction {
  @SerializedName("createSubscription")
  private CreateSubscription createSubscription = null;

  @SerializedName("triggerDates")
  private List<TriggerDate> triggerDates = new ArrayList<TriggerDate>();

  @SerializedName("type")
  private String type = null;

  public OrderAction createSubscription(CreateSubscription createSubscription) {
    this.createSubscription = createSubscription;
    return this;
  }

   /**
   * Get createSubscription
   * @return createSubscription
  **/
  @ApiModelProperty(required = true, value = "")
  public CreateSubscription getCreateSubscription() {
    return createSubscription;
  }

  public void setCreateSubscription(CreateSubscription createSubscription) {
    this.createSubscription = createSubscription;
  }

  public OrderAction triggerDates(List<TriggerDate> triggerDates) {
    this.triggerDates = triggerDates;
    return this;
  }

  public OrderAction addTriggerDatesItem(TriggerDate triggerDatesItem) {
    this.triggerDates.add(triggerDatesItem);
    return this;
  }

   /**
   * Get triggerDates
   * @return triggerDates
  **/
  @ApiModelProperty(required = true, value = "")
  public List<TriggerDate> getTriggerDates() {
    return triggerDates;
  }

  public void setTriggerDates(List<TriggerDate> triggerDates) {
    this.triggerDates = triggerDates;
  }

  public OrderAction type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderAction orderAction = (OrderAction) o;
    return Objects.equals(this.createSubscription, orderAction.createSubscription) &&
        Objects.equals(this.triggerDates, orderAction.triggerDates) &&
        Objects.equals(this.type, orderAction.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createSubscription, triggerDates, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderAction {\n");
    
    sb.append("    createSubscription: ").append(toIndentedString(createSubscription)).append("\n");
    sb.append("    triggerDates: ").append(toIndentedString(triggerDates)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

