/*
 * Zuora Copy
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.zuora.prototype.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TriggerDate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-20T00:16:03.519Z")



public class TriggerDate {
  @SerializedName("name")
  private String name = null;

  @SerializedName("triggerDate")
  private String triggerDate = null;

  public TriggerDate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TriggerDate triggerDate(String triggerDate) {
    this.triggerDate = triggerDate;
    return this;
  }

   /**
   * Get triggerDate
   * @return triggerDate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTriggerDate() {
    return triggerDate;
  }

  public void setTriggerDate(String triggerDate) {
    this.triggerDate = triggerDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TriggerDate triggerDate = (TriggerDate) o;
    return Objects.equals(this.name, triggerDate.name) &&
        Objects.equals(this.triggerDate, triggerDate.triggerDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, triggerDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TriggerDate {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    triggerDate: ").append(toIndentedString(triggerDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

